# Generated by Django 6.0.1 on 2026-01-26 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('initials', models.CharField(blank=True, max_length=5)),
                ('department', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('publications_count', models.IntegerField(default=0)),
                ('h_index', models.IntegerField(default=0)),
                ('citations', models.IntegerField(default=0)),
                ('tags', models.TextField(help_text="Comma-separated tags e.g. 'AI, Flutter'")),
            ],
        ),
        migrations.CreateModel(
            name='SDG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CollaborationOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('match_score', models.IntegerField()),
                ('reason', models.TextField()),
                ('researcher_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities_as_r1', to='core.researcher')),
                ('researcher_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities_as_r2', to='core.researcher')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed')], max_length=50)),
                ('start_year', models.IntegerField()),
                ('members', models.ManyToManyField(related_name='projects', to='core.researcher')),
                ('sdgs', models.ManyToManyField(related_name='projects', to='core.sdg')),
            ],
        ),
    ]
